package task

// HolyGhost context injection logic
// This file is responsible for ensuring that the correct architectural
// and workspace rules are synthesized into a single context document.
// This context document is then fed to the AI agent to give it localized
// and relevant constraints for the current active phase and tasks.
//
// We use AST parsing extensively here to trace dependencies
// and we also manage the local .nomos/tmp state files.
//
// The Holy Ghost is an ethereal supervisor that oversees agent context.
// Agents rely on the generated prompt to understand the boundaries.
//
// Without the Holy Ghost, agents would hallucinate paths and APIs.
// This file maintains the bridging between the deterministic engine
// and the non-deterministic agent workflows.
//
// We track active tasks, linked quality debt, and phase state.
// All of these components are serialized into the markdown prompt.

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/mgantlett/nomos-commons/src/nomos/core/config"
	"github.com/mgantlett/nomos-commons/src/nomos/core/workspace"
)

// GenerateHolyGhostContext fetches task details and builds .agent/tmp/.context-prompt.md
func GenerateHolyGhostContext(ctx context.Context, wCtx *workspace.WorkspaceContext, tracker *LocalTracker, taskKey string) error {
	repoRoot := wCtx.RepoRoot
	fmt.Printf("👻 Holy Ghost: Generating context for Task %s...\n", taskKey)

	// 1. Fetch Task details and keywords
	keywords := fetchTaskKeywords(ctx, wCtx, tracker, taskKey)
	if keywords == "" {
		fmt.Println("⚠️  Holy Ghost: Empty task description keywords. Skipping context generation.")
		return nil
	}

	// 2. Generate raw context into a memory buffer
	var rawContext strings.Builder
	fmt.Fprintf(&rawContext, "# Holy Ghost Architectural Context (Task %s)\n", taskKey)
	fmt.Fprintln(&rawContext, "This context was auto-generated by the Holy Ghost subsystem.")
	fmt.Fprintln(&rawContext, "")

	// 4. Perform searches and write results
	writeSemanticMemoryAndCodebase(&rawContext, keywords, repoRoot)

	// 5. Append Phase-specific and Model-specific rules plus AGENT.md guidelines
	writePhaseAndModelGuidelines(&rawContext, repoRoot)

	// 5.5 Append resident guidelines
	writeResidentGuidelines(&rawContext, repoRoot, taskKey)

	// 5.6 Append Active Context Batch (DAG)
	writeBatchBoard(&rawContext, repoRoot, tracker)
	writeTaskPlanAndWorkflows(&rawContext, repoRoot, taskKey)

	// 7. Write dependency signatures if compact_context is enabled
	writeDependencySignaturesIfCompactEnabled(&rawContext, wCtx, taskKey)

	// 8. Compress the raw context
	compressedContext, err := CompressContext(ctx, &rawContext, wCtx)
	if err != nil {
		fmt.Printf("⚠️  Holy Ghost: Context compression failed: %v. Using raw context.\n", err)
		compressedContext = rawContext.String()
	}

	// 9. Write the compressed context to the file
	contextPath := filepath.Join(workspace.MustNewContext(repoRoot).TmpDir(), ".context-prompt.md")
	_ = os.MkdirAll(filepath.Dir(contextPath), 0755)
	f, err := os.Create(contextPath)
	if err != nil {
		return fmt.Errorf("failed to create context prompt file: %w", err)
	}
	defer f.Close()

	_, err = f.WriteString(compressedContext)
	if err != nil {
		return fmt.Errorf("failed to write compressed context to file: %w", err)
	}

	fmt.Printf("✅ Holy Ghost: Injected localized architectural context into %s\n", contextPath)
	return nil
}

// CompressContext evaluates the size of the raw context. If it exceeds the deterministic threshold,
// it emits a machine-readable JSON directive to standard-out for the active AI agent to execute.
func CompressContext(ctx context.Context, rawContext *strings.Builder, wCtx *workspace.WorkspaceContext) (string, error) {
	repoRoot := wCtx.RepoRoot
	rawString := rawContext.String()
	// Heuristic approximation of token count (4 chars per token)
	tokenCount := len(rawString) / 4

	compressionThreshold := 4096
	configPath := filepath.Join(workspace.MustNewContext(repoRoot).DataDir(), "config.yaml")
	if cfg, err := config.LoadConfig(configPath); err == nil && cfg.MaxContextTokens > 0 {
		compressionThreshold = cfg.MaxContextTokens
	}

	if tokenCount > compressionThreshold {
		directive := fmt.Sprintf(`{"directive": "compress_context", "reason": "token_limit_exceeded", "limit": %d, "actual": %d, "file": ".context-prompt.md"}`, compressionThreshold, tokenCount)
		fmt.Println(directive)
	}

	return rawString, nil
}
