package verify

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestMatchWildcardExclude(t *testing.T) {
	require.True(t, matchWildcardExclude("src/foo.go", "src/**"))
	require.True(t, matchWildcardExclude("src/bar/baz.go", "src/**"))
	require.False(t, matchWildcardExclude("cmd/foo.go", "src/**"))

	require.True(t, matchWildcardExclude("test.go", "*.go"))
	require.True(t, matchWildcardExclude("foo/bar/test.go", "foo/bar/*.go"))
}

func TestIsGeneratedFile(t *testing.T) {
	tempDir, err := os.MkdirTemp("", "nomos-dod-gen-*")
	require.NoError(t, err)
	defer os.RemoveAll(tempDir)

	genPath := filepath.Join(tempDir, "gen.go")
	os.WriteFile(genPath, []byte("// Code generated by something. DO NOT EDIT.\npackage main\n"), 0644)
	require.True(t, isGeneratedFile(genPath))

	normalPath := filepath.Join(tempDir, "normal.go")
	os.WriteFile(normalPath, []byte("package main\n"), 0644)
	require.False(t, isGeneratedFile(normalPath))
}
