// Package cmd implements the command-line interface suite for Nomos OS.
// This module orchestrates git commit creation with structured reasoning, phase compliance,
// Definition of Done (DoD) verification gates, and Product Owner approval hooks.
package cmd

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/mgantlett/nomos-commons/src/nomos/core/workspace"

	statepkg "github.com/mgantlett/nomos-commons/src/nomos/core/state"
	"github.com/mgantlett/nomos-commons/src/nomos/core/synapse"

	"github.com/mgantlett/nomos-commons/src/nomos/core/telemetry"
	"github.com/mgantlett/nomos-os/src/nomos/modules/task"
	"github.com/mgantlett/nomos-os/src/nomos/modules/verify"
	"github.com/spf13/cobra"
)

// Global flags and command definition for the nomos commit CLI entry point.
var (
	commitFile string
	commitMsg  string

	// commitCmd defines the cobra command for executing structured commits.
	// This command enforces the Definition of Done (DoD) verification gates
	// and validates that the workspace phase state permits committing.
	commitCmd = &cobra.Command{
		Use:   "commit",
		Short: "Stage and commit passing code changes with structured reasoning",
		Long:  `Run DoD verification gates and commit passing changes to the repository with structured reasoning.`,
		RunE:  runCommitCmd,
	}
)

// runCommitCmd handles the core commit orchestration lifecycle.
// It validates branch protection, runs verification gates, resolves the phase state, executes the commit, and logs telemetry.
func runCommitCmd(cmd *cobra.Command, args []string) error {
	root, err := os.Getwd()
	if err != nil {
		return err
	}
	repoRoot := findRepoRoot(root)
	if err := enforceWorktreeZone(func() *workspace.WorkspaceContext { c, _ := workspace.NewContext(repoRoot); return c }(), "commit"); err != nil {
		return err
	}

	if err := enforceTaskDiscipline(root); err != nil {
		return err
	}

	if err := enforceBranchProtection(root); err != nil {
		return err
	}

	preStaged, err := checkStagedFiles(root)
	if err != nil {
		return err
	}

	if err := runDoDGates(root); err != nil {
		return err
	}

	// Re-stage the captured files in case gofmt altered them during DoD gates
	if len(preStaged) > 0 {
		addArgs := append([]string{"add"}, preStaged...)
		addCmd := exec.Command("git", addArgs...)
		addCmd.Dir = root
		_ = addCmd.Run()
	}

	state, err := resolvePhaseState(root)
	if err != nil {
		return err
	}

	if err := executeGitCommit(root, state); err != nil {
		return err
	}

	appendGitNotes(root, state)
	return nil
}

// enforceTaskDiscipline ensures that manual commits are not executed during an active task cycle.
func enforceTaskDiscipline(root string) error {
	taskID := verify.GetActiveTaskId(root)
	if taskID != "" && taskID != "UNKNOWN" {
		return fmt.Errorf("DDP VIOLATION: Manual 'nomos commit' is strictly forbidden during an active task cycle. You must execute the atomic release using 'nomos task merge -F walkthrough.md'")
	}
	return nil
}

// enforceBranchProtection validates that the current git branch is not a protected branch (e.g. master or main).
// This prevents direct commits to production branches, forcing developers to use feature branches.
func enforceBranchProtection(root string) error {
	out, errBranch := exec.Command("git", "rev-parse", "--abbrev-ref", "HEAD").Output()
	if errBranch != nil {
		return nil
	}
	currBranch := strings.TrimSpace(string(out))
	if currBranch == "master" || currBranch == "main" {
		return fmt.Errorf("direct commits to production branch '%s' are strictly forbidden by Nomos Branch Protection Gate. Switch to 'develop' or a feature branch", currBranch)
	}
	return nil
}

// checkStagedFiles audits the staged files to ensure they don't violate atomic commit thresholds or touch generated files.
// It also extracts the pre-staged snapshot before the DoD gate runs.
func checkStagedFiles(root string) ([]string, error) {
	gitDiffCmd := exec.Command("git", "diff", "--cached", "--name-only")
	gitDiffCmd.Dir = root
	out, _ := gitDiffCmd.Output()
	var preStaged []string
	for _, line := range strings.Split(string(out), "\n") {
		if file := strings.TrimSpace(line); file != "" {
			if workspace.IsInternalAgentDir(file) {
				return nil, fmt.Errorf("❌ FATAL: Attempted to mutate a generated file!\nYou have staged changes to '%s'. These files are ephemeral and generated by the Rehydrator.\nTo permanently alter this workflow or protocol, you MUST modify the source substrate located in 'src/nomos/core/assets/' instead.", file)
			}
			preStaged = append(preStaged, file)
		}
	}

	return preStaged, nil
}

// runDoDGates executes the rigorous Definition of Done (DoD) verification checks.
// It sets an environment variable to prevent recursive hook execution and runs all configured quality gates.
func runDoDGates(root string) error {
	synapse.Info("%s", fmt.Sprint("🛡️  Running Definition of Done (DoD) verification gates..."))
	os.Setenv("NOMOS_IN_GIT_HOOK", "1")
	defer os.Unsetenv("NOMOS_IN_GIT_HOOK")
	if err := verify.VerifyDoD(func() *workspace.WorkspaceContext { c, _ := workspace.NewContext(root); return c }()); err != nil {
		return fmt.Errorf("definition of done checks failed, commit aborted: %w", err)
	}
	synapse.Info("%s", fmt.Sprint("✅ DoD verification gates passed."))
	return nil
}

// resolvePhaseState retrieves the current workspace phase state and ensures the workspace is in the correct phase for committing.
// It enforces that the agent has explicitly transitioned to the EDIT or REVIEW phase before modifying codebase state.
func resolvePhaseState(root string) (*task.PhaseState, error) {
	repoRoot := findRepoRoot(root)
	if err := verify.CheckPOCommitApproval(repoRoot); err != nil {
		return nil, err
	}
	state, _ := task.GetPhaseState(func() *workspace.WorkspaceContext { c, _ := workspace.NewContext(repoRoot); return c }())
	if state == nil || state.TaskId == "" {
		return nil, fmt.Errorf("Commit Blocked: Missing active task binding. All commits must be bound to an active Task per DoD constraints")
	}
	if state.CurrentPhase == statepkg.PhaseEdit {
		// Valid EDIT phase; user is making a progressive commit. No prompt needed.
	} else if state.CurrentPhase != statepkg.PhaseEdit && state.CurrentPhase != statepkg.PhaseReview {
		return nil, fmt.Errorf("cryptographic phase token validation failed: workspace is not in EDIT phase (current: %s)", state.CurrentPhase)
	}
	return state, nil
}

// executeGitCommit formats the arguments and executes the underlying git commit shell command.
// It binds the standard output and error streams to the terminal for transparent logging.
func executeGitCommit(root string, state *task.PhaseState) error {
	gitArgs, err := resolveCommitArgs(root, commitFile, commitMsg, state)
	if err != nil {
		return err
	}
	gitCmd := exec.Command("git", gitArgs...)
	gitCmd.Dir = root
	gitCmd.Stdout = os.Stdout
	gitCmd.Stderr = os.Stderr
	gitCmd.Stdin = os.Stdin
	if err := gitCmd.Run(); err != nil {
		return fmt.Errorf("git commit failed: %w", err)
	}
	emitCommitTelemetry(root)
	return nil
}

// emitCommitTelemetry extracts the first line of the created git commit message
// and emits a telemetry event for monitoring system productivity and agent actions.
func emitCommitTelemetry(root string) {
	firstLineMsg := "Git commit completed"
	gitLogCmd := exec.Command("git", "log", "-1", "--pretty=%s")
	gitLogCmd.Dir = root
	if out, err := gitLogCmd.Output(); err == nil {
		firstLineMsg = strings.TrimSpace(string(out))
	}
	_ = telemetry.EmitEvent(root, "commit", firstLineMsg)
}

// appendGitNotes reads the walkthrough artifact created during the task lifecycle
// and appends it to the git notes ref 'refs/notes/agent' for future context retrieval.
func appendGitNotes(root string, state *task.PhaseState) {
	if state == nil || state.TaskId == "" {
		return
	}
	// The Walkthrough MUST be present if they are committing Phase modifications.
	walkthroughPath := workspace.MustNewContext(root).WalkthroughStagingPath()
	b, err := os.ReadFile(walkthroughPath)
	if err != nil {
		return
	}
	payload := fmt.Sprintf(`{"explainers": [{"title": "Walkthrough %s", "content": %q}]}`, state.TaskId, string(b))
	notesCmd := exec.Command("git", "notes", "--ref=refs/notes/agent", "append", "-m", payload, "HEAD")
	notesCmd.Dir = root
	if err := notesCmd.Run(); err == nil {
		_ = os.Remove(walkthroughPath)
	}
}

func init() {
	commitCmd.Flags().StringVarP(&commitFile, "file", "F", "", "Read message from file")
	commitCmd.Flags().StringVarP(&commitMsg, "message", "m", "", "Commit message")
}

// readCommitMsgContent reads commit message content from flags or temporary file location.
func readCommitMsgContent(root, commitFile, commitMsg string) (string, error) {
	if commitFile != "" {
		b, err := os.ReadFile(commitFile)
		if err == nil {
			return string(b), nil
		}
	} else if commitMsg != "" {
		return commitMsg, nil
	}
	templatePath := filepath.Join(workspace.MustNewContext(root).TmpDir(), "commit_msg.md")
	b, err := os.ReadFile(templatePath)
	if err == nil {
		return string(b), nil
	}
	return "", fmt.Errorf("missing commit message: please provide a message via -m, -F, or place it in .agent/tmp/commit_msg.md")
}

// resolveCommitArgs constructs the appropriate arguments for the git commit command.
func resolveCommitArgs(root, commitFile, commitMsg string, state *task.PhaseState) ([]string, error) {
	var gitArgs []string
	gitArgs = append(gitArgs, "commit")

	if state != nil && state.CurrentPhase == statepkg.PhaseIdle {
		metaOnly, errMeta := verify.IsMetadataOnly(root)
		if errMeta == nil && metaOnly {
			gitArgs = append(gitArgs, "--no-verify")
		}
	}

	msgContent, err := readCommitMsgContent(root, commitFile, commitMsg)
	if err != nil {
		return nil, err
	}

	msgContent, err = validateCommitMessage(root, msgContent, state)
	if err != nil {
		return nil, err
	}

	// Write to an ephemeral file to pass to git commit -F
	tmpFile := filepath.Join(workspace.MustNewContext(root).TmpDir(), "nomos_commit_in_flight.md")
	if err := os.WriteFile(tmpFile, []byte(msgContent), 0644); err != nil {
		return nil, fmt.Errorf("failed to write transient commit message: %w", err)
	}

	gitArgs = append(gitArgs, "-F", tmpFile, "--no-edit")
	return gitArgs, nil
}

// parseCommitMessage checks for the required Dual-Layer format and extracts the title.
func parseCommitMessage(msgContent string) (string, error) {
	var title string
	lines := strings.Split(msgContent, "\n")
	for _, line := range lines {
		trim := strings.TrimSpace(line)
		if trim != "" && title == "" {
			title = trim
			break
		}
	}

	if title == "" {
		return "", fmt.Errorf("❌ Atomic Violation: Commit message must have a title")
	}

	// We now use bolded text headings for structured reasoning
	lowerMsg := strings.ToLower(msgContent)
	if !strings.Contains(lowerMsg, "**impact list:**") && !strings.Contains(lowerMsg, "**resolution details:**") {
		return "", fmt.Errorf("❌ Atomic Violation: Commit message is missing the bolded text headings (e.g. '**Impact List:**' or '**Resolution Details:**')")
	}
	return title, nil
}

// appendTelemetrySection inspects telemetry metrics for OpenCode agent executions
// and appends a Markdown telemetry summary to the end of the commit message.
func appendTelemetrySection(msgContent string, root string, taskId string) string {
	opm, err := telemetry.ExtractOpenCodeMetrics(root, taskId)
	if err != nil || opm == nil {
		return msgContent
	}
	var sb strings.Builder
	sb.WriteString("\n## 📊 Telemetry\n")
	sb.WriteString(fmt.Sprintf("- **Agent:** swarm:opencode\n"))
	sb.WriteString(fmt.Sprintf("- **Prompt Tokens:** %d\n", opm.TotalPromptTokens))
	sb.WriteString(fmt.Sprintf("- **Completion Tokens:** %d\n", opm.TotalCompletionTokens))
	sb.WriteString(fmt.Sprintf("- **Cost:** $%.4f\n", opm.TotalCost))
	return msgContent + sb.String()
}

// validateCommitMessage checks if the commit message conforms to the atomic commit specification.
// It auto-injects the Task ID prefix and formats any telemetry into Markdown.
func validateCommitMessage(root, msgContent string, state *task.PhaseState) (string, error) {
	// Parse title from commit message body and enforce bolded heading presence
	title, err := parseCommitMessage(msgContent)
	if err != nil {
		return "", err
	}

	// Verify that an active task ID binding exists for tracking
	if state == nil || state.TaskId == "" {
		return "", fmt.Errorf("❌ Atomic Violation: Commit message must be bound to a Task ID")
	}

	// Strip existing task references from the beginning to avoid duplicate task prefixes
	re := regexp.MustCompile(fmt.Sprintf(`(?i)^(\[Task\s+%s\]\s*)?(Task\s+%s\b[^:]*:\s*)?`, state.TaskId, state.TaskId))
	cleanTitle := re.ReplaceAllString(title, "")
	cleanTitle = strings.TrimSpace(cleanTitle)

	// Format standardized title string containing active task ID
	newTitle := fmt.Sprintf("[Task %s] %s", state.TaskId, cleanTitle)
	if strings.HasPrefix(cleanTitle, "**Impact") || strings.HasPrefix(cleanTitle, "**Resolution") {
		newTitle = fmt.Sprintf("[Task %s]\n\n%s", state.TaskId, cleanTitle)
	}

	if title != newTitle {
		msgContent = strings.Replace(msgContent, title, newTitle, 1)
	}

	// Append OpenCode agent telemetry section if available
	msgContent = appendTelemetrySection(msgContent, root, state.TaskId)
	return msgContent, nil
}
